In [248]:
import pandas as pd
import numpy as np

In [249]:
data = pd.read_csv('/Users/danialnekounam/Desktop/car.csv')
data

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [250]:
dummies=pd.get_dummies(data,columns=['vhigh','vhigh.1','2','2.1','small','low'])
dummies

unacc  vhigh_high  vhigh_low  vhigh_med  vhigh_vhigh  vhigh.1_high  \
0     unacc           0          0          0            1             0   
1     unacc           0          0          0            1             0   
2     unacc           0          0          0            1             0   
3     unacc           0          0          0            1             0   
4     unacc           0          0          0            1             0   
...     ...         ...        ...        ...          ...           ...   
1722   good           0          1          0            0             0   
1723  vgood           0          1          0            0             0   
1724  unacc           0          1          0            0             0   
1725   good           0          1          0            0             0   
1726  vgood           0          1          0            0             0   

      vhigh.1_low  vhigh.1_med  vhigh.1_vhigh  2_2  ...  2_5more  2.1_2  \
0               0            0              1    1  ...        0      1   
1               0            0              1    1  ...        0      1   
2               0            0              1    1  ...        0      1   
3               0            0              1    1  ...        0      1   
4               0            0              1    1  ...        0      1   
...           ...          ...            ...  ...  ...      ...    ...   
1722            1            0              0    0  ...        1      0   
1723            1            0              0    0  ...        1      0   
1724            1            0              0    0  ...        1      0   
1725            1            0              0    0  ...        1      0   
1726            1            0              0    0  ...        1      0   

      2.1_4  2.1_more  small_big  small_med  small_small  low_high  low_low  \
0         0         0          0          0            1         0        0   
1         0         0          0          0            1         1        0   
2         0         0          0          1            0         0        1   
3         0         0          0          1            0         0        0   
4         0         0          0          1            0         1        0   
...     ...       ...        ...        ...          ...       ...      ...   
1722      0         1          0          1            0         0        0   
1723      0         1          0          1            0         1        0   
1724      0         1          1          0            0         0        1   
1725      0         1          1          0            0         0        0   
1726      0         1          1          0            0         1        0   

      low_med  
0           1  
1           0  
2           0  
3           1  
4           0  
...       ...  
1722        1  
1723        0  
1724        0  
1725        1  
1726        0  

[1727 rows x 22 columns]

In [251]:
 print ("Dataset: ",dummies.head())

Dataset:     unacc  vhigh_high  vhigh_low  vhigh_med  vhigh_vhigh  vhigh.1_high  \
0  unacc           0          0          0            1             0   
1  unacc           0          0          0            1             0   
2  unacc           0          0          0            1             0   
3  unacc           0          0          0            1             0   
4  unacc           0          0          0            1             0   

   vhigh.1_low  vhigh.1_med  vhigh.1_vhigh  2_2  ...  2_5more  2.1_2  2.1_4  \
0            0            0              1    1  ...        0      1      0   
1            0            0              1    1  ...        0      1      0   
2            0            0              1    1  ...        0      1      0   
3            0            0              1    1  ...        0      1      0   
4            0            0              1    1  ...        0      1      0   

   2.1_more  small_big  small_med  small_small  low_high  low_low  low_med  

In [252]:
X = dummies.values[:, 1:21]
Y = dummies.values[:, 0]
df = pd.DataFrame(dummies)
dummies
#col_name='low_med'
#index_no = df.columns.get_loc(col_name)
#print("Index of {} column in given dataframe is : {}".format(col_name, index_no))



unacc  vhigh_high  vhigh_low  vhigh_med  vhigh_vhigh  vhigh.1_high  \
0     unacc           0          0          0            1             0   
1     unacc           0          0          0            1             0   
2     unacc           0          0          0            1             0   
3     unacc           0          0          0            1             0   
4     unacc           0          0          0            1             0   
...     ...         ...        ...        ...          ...           ...   
1722   good           0          1          0            0             0   
1723  vgood           0          1          0            0             0   
1724  unacc           0          1          0            0             0   
1725   good           0          1          0            0             0   
1726  vgood           0          1          0            0             0   

      vhigh.1_low  vhigh.1_med  vhigh.1_vhigh  2_2  ...  2_5more  2.1_2  \
0               0            0              1    1  ...        0      1   
1               0            0              1    1  ...        0      1   
2               0            0              1    1  ...        0      1   
3               0            0              1    1  ...        0      1   
4               0            0              1    1  ...        0      1   
...           ...          ...            ...  ...  ...      ...    ...   
1722            1            0              0    0  ...        1      0   
1723            1            0              0    0  ...        1      0   
1724            1            0              0    0  ...        1      0   
1725            1            0              0    0  ...        1      0   
1726            1            0              0    0  ...        1      0   

      2.1_4  2.1_more  small_big  small_med  small_small  low_high  low_low  \
0         0         0          0          0            1         0        0   
1         0         0          0          0            1         1        0   
2         0         0          0          1            0         0        1   
3         0         0          0          1            0         0        0   
4         0         0          0          1            0         1        0   
...     ...       ...        ...        ...          ...       ...      ...   
1722      0         1          0          1            0         0        0   
1723      0         1          0          1            0         1        0   
1724      0         1          1          0            0         0        1   
1725      0         1          1          0            0         0        0   
1726      0         1          1          0            0         1        0   

      low_med  
0           1  
1           0  
2           0  
3           1  
4           0  
...       ...  
1722        1  
1723        0  
1724        0  
1725        1  
1726        0  

[1727 rows x 22 columns]

In [253]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( 
X, Y, test_size = 0.3, random_state = 100)
X_train 
X_test

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1]], dtype=object)

In [254]:
from sklearn.tree import DecisionTreeClassifier
clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 100,max_depth=3, min_samples_leaf=21)
clf_gini.fit(X_train, y_train)
clf_gini.score(X_test,y_test)

0.7957610789980732

In [255]:
clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 21)
clf_entropy.fit(X_train, y_train)
clf_entropy

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=21,
                       random_state=100)

In [256]:

y_pred = clf_entropy.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
['unacc' 'acc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'acc' 'unacc'
 'unacc' 'unacc' 'unacc' 'unacc' 'acc' 'unacc' 'unacc' 'unacc' 'unacc'
 'unacc' 'unacc' 'acc' 'unacc' 'acc' 'unacc' 'acc' 'unacc' 'unacc' 'unacc'
 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'acc' 'acc' 'acc' 'acc' 'acc'
 'acc' 'acc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc'
 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'acc' 'unacc' 'unacc' 'unacc'
 'unacc' 'acc' 'unacc' 'acc' 'acc' 'unacc' 'unacc' 'unacc' 'acc' 'unacc'
 'acc' 'acc' 'acc' 'acc' 'unacc' 'acc' 'unacc' 'acc' 'unacc' 'acc' 'unacc'
 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc'
 'unacc' 'acc' 'acc' 'unacc' 'unacc' 'acc' 'acc' 'acc' 'acc' 'acc' 'acc'
 'acc' 'unacc' 'unacc' 'acc' 'acc' 'unacc' 'unacc' 'unacc' 'unacc' 'unacc'
 'acc' 'unacc' 'unacc' 'unacc' 'acc' 'unacc' 'acc' 'unacc' 'unacc' 'unacc'
 'unacc' 'unacc' 'acc' 'acc' 'unacc' 'acc' 'unacc' 'unacc' 'unacc' 'unacc'
 'unacc' 'acc' 'unacc' 'unacc' 'acc' 

In [260]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
encoded_y = label_encoder.fit_transform(y)
label_encoder_name_mapping = dict(zip(label_encoder.classes_,
                                         label_encoder.transform(label_encoder.classes_)))
print("Mapping of Label Encoded Classes", label_encoder_name_mapping, sep="\n")
print("Label Encoded Target Variable", encoded_y, sep="\n")


Mapping of Label Encoded Classes
{'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
Label Encoded Target Variable
[2 2 2 ... 2 1 3]


/Users/danialnekounam/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [259]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
print("Confusion Matrix: ",
        confusion_matrix(y_test, y_pred))
      
print ("Accuracy : ",
    accuracy_score(y_test,y_pred)*100)
      
print("Report : ",
    classification_report(y_test, y_pred))
  

Confusion Matrix:  [[ 79   0  26   0]
 [ 22   0   0   0]
 [ 38   0 334   0]
 [ 20   0   0   0]]
Accuracy :  79.57610789980733
Report :                precision    recall  f1-score   support

         acc       0.50      0.75      0.60       105
        good       0.00      0.00      0.00        22
       unacc       0.93      0.90      0.91       372
       vgood       0.00      0.00      0.00        20

    accuracy                           0.80       519
   macro avg       0.36      0.41      0.38       519
weighted avg       0.77      0.80      0.78       519



/Users/danialnekounam/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/danialnekounam/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/danialnekounam/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r